function VcLp(){function n(a){var b=document.URL,c=u();null!=c&&(b=c);b=b.match(/[?&]vc_lpp=([^&]+)/);if(null==b)q(void 0,a);else{b=b[1];c="";try{c=v(b)}catch(r){q(void 0,a);return}q(c,a);a=z(c);var e=Math.floor((new Date).getTime()/1E3);a:if(c="l",null!=a&&!(e>a.sig_exp+10800)){if(null!=a.beacon&&(e=a.beacon))try{var d=void 0,k=void 0,h=document.URL,l=u();null!=l&&(h=l);var g=h.match(/[?&]vo__ih=([^&]+)/);null!=g&&(d=g[1]);var m=h.match(/[?&]vo__uri=([^&]+)/);null!=m&&(k=m[1]);path=v(e);h="https://ptb.valuecommerce.com"+
path;void 0!==d&&(h+="&ih="+d);void 0!==k&&(h+="&vcurl="+k);navigator.sendBeacon(h)}catch(r){}l="";try{l=(new Date(1E3*a.exp_ut)).toUTCString()}catch(r){break a}h=!1;g=location.search.match(/[?&]vc_lpp_src=([^&]+)/);(null==g?0:"wv"===g[1])&&(t()&&(!t()||-1===navigator.userAgent.indexOf("; wv"))||w()&&!x(a.adv_id,a.val))&&(c=a.lpp_version,h=!0);if(!x(a.adv_id,a.val)||h){g="";try{var f=document.createElement("a");f.href=document.URL;g=f.hostname}catch(r){}f=g.split(".");g=f.length;3<=g&&(m="."+f[g-
3]+"."+f[g-2]+"."+f[g-1],y(a.adv_id,l,c,a.val,m));2<=g&&(m="."+f[g-2]+"."+f[g-1],y(a.adv_id,l,c,a.val,m))}f=a.val;"undefined"!=typeof localStorage&&null!=localStorage?(l=localStorage.getItem("_vc_lsc_"+a.adv_id),f=(new RegExp("[0-9a-zA-Z]s"+f+"&")).test(l)):f=!1;f&&!h||"undefined"==typeof localStorage||null==localStorage||localStorage.setItem("_vc_lsc_"+a.adv_id,c+"s"+a.val+"&"+a.exp_ut)}if((t()&&-1!==navigator.userAgent.indexOf("; wv")||w())&&null!==a&&3==a.lpp_version)for(b="vc_lpp="+b+"&vc_lpp_src=wv",
a=document.getElementsByTagName("a"),c=0;c<a.length;c++)f=a[c],f.host===location.host&&(f.search+=(-1!==f.search.indexOf("?")?"&":"?")+b)}}function q(a,b){if("undefined"!=typeof a){a="undefined"!==typeof a?"?p="+encodeURIComponent(a)+"&":"?";"undefined"!==typeof b&&(a+="vf="+encodeURIComponent(b)+"&");b=a;a="";try{var c=document.createElement("a");c.href=document.URL;a=encodeURIComponent(c.protocol+"//"+c.hostname+"/")}catch(e){}a=b+("_s="+a+"&_rand="+Math.random());c="https://b.imgvc.com/l"+a;document.createElement("img").src=
c}}function z(a){var b=a.split("&");if(5>b.length)return null;var c=0,e=1,d=2,k=3;b[0].match(/^[1-9]$/)&&(c=b[0],e=2,d=3,k=4,a=b[5]);e=parseInt(b[e],16);if(isNaN(e))return null;d=parseInt(b[d],16);if(isNaN(d))return null;k=parseInt(b[k],16);if(isNaN(k))return null;var h=null;2==c&&(h=b[6]);return{lpp_version:c,sig_exp:e,adv_id:d,exp_ut:k,val:a,beacon:h}}function x(a,b){return(new RegExp("(^|; *)_vc_citi_"+a+"=[0-9a-zA-Z]"+b+"(;|$)")).test(document.cookie)}function y(a,b,c,e,d){document.cookie="_vc_citi_"+
a+"="+c+e+"; expires="+b+"; path=/; domain="+d}function p(a){if(65<=a&&90>=a)return a-65;if(97<=a&&122>=a)return a-97+26;if(48<=a&&57>=a)return a-48+52;if(45==a)return 62;if(95==a)return 63;throw Error("unvalid char");}function v(a){var b="";try{var c=a;c=c.replace(/-/g,"+").replace(/_/g,"/");return decodeURIComponent(A(atob(c)))}catch(k){}c=0;for(var e=a.length;c<e;c+=4){var d=[0,0,0,0];d[0]=p(a.charCodeAt(c));e>c+1&&(d[1]=p(a.charCodeAt(c+1)));e>c+2&&(d[2]=p(a.charCodeAt(c+2)));e>c+3&&(d[3]=p(a.charCodeAt(c+
3)));c+3<e?(b+=String.fromCharCode((d[0]<<2)+(d[1]>>4)&255),b+=String.fromCharCode((d[1]<<4)+(d[2]>>2)&255),b+=String.fromCharCode((d[2]<<6)+d[3]&255)):c+2<e?(b+=String.fromCharCode((d[0]<<2)+(d[1]>>4)&255),b+=String.fromCharCode((d[1]<<4)+(d[2]>>2)&255),b+=String.fromCharCode(d[2]<<6&255)):c+1<e?(b+=String.fromCharCode((d[0]<<2)+(d[1]>>4)&255),b+=String.fromCharCode(d[1]<<4&255)):c<e&&(b+=String.fromCharCode(d[0]<<2&255))}return b.replace(/\0/g,"")}function A(a){return a.replace(/[^a-zA-Z0-9@*_+\-./]/g,
function(b){b=b.charCodeAt(0);return 255>=b?"%"+("00"+b.toString(16)).slice(-2).toUpperCase():"%u"+("0000"+b.toString(16)).slice(-4).toUpperCase()})}function u(){var a=null;if("undefined"!==typeof document.querySelectorAll)for(var b=document.querySelectorAll("div[data-vc-lp-url]"),c=0;c<b.length&&(a=b[c].getAttribute("data-vc-lp-url"),null===a||""===a);c++);else for(b=document.getElementsByTagName("div"),c=0;c<b.length&&(a=b[c].getAttribute("data-vc-lp-url"),null===a||""===a);c++);return a}function t(){return-1!==
navigator.userAgent.indexOf("Android")}function w(){return-1!==navigator.userAgent.indexOf("iPhone;")||-1!==navigator.userAgent.indexOf("iPad;")||-1!==navigator.userAgent.indexOf("iPod touch;")}this.finishLoad=function(){var a=document.getElementById("ValueCommerceLpOpts");if(a&&a.hasAttribute("data-vc-opt-event-driven-disabled"))n(void 0);else{var b=document.createElement("img"),c=document.createElement("canvas");b.addEventListener&&"undefined"!=typeof c?(b.addEventListener("load",function(){try{c.width=
b.naturalWidth;c.height=b.naturalHeight;c.getContext("2d").drawImage(b,0,0);var e=c.toDataURL("image/png");n(e.replace(/^data:image\/(png|jpg);base64,/,""))}catch(d){n(void 0)}},!1),b.crossOrigin="anonymous",b.style.display="none",b.src="https://a.imgvc.com/i/bf.png?v=1",document.getElementsByTagName("body")[0].appendChild(b)):n(void 0)}}}
if("undefined"==typeof vclpObj){var vclpObj=new VcLp;if(document.addEventListener)"loading"!=document.readyState?vclpObj.finishLoad():document.addEventListener("DOMContentLoaded",vclpObj.finishLoad,!1);else if(document.attachEvent){var CheckReadyState=function(){"complete"==document.readyState&&(document.detachEvent("onreadystatechange",CheckReadyState),vclpObj.finishLoad())};document.attachEvent("onreadystatechange",CheckReadyState);(function(){try{document.documentElement.doScroll("left")}catch(n){return}document.detachEvent("onreadystatechange",
CheckReadyState);vclpObj.finishLoad()})()}else vclpObj.finishLoad()};
